/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Check
         * @description Evaluate every unbreached falsifier on every LIVE recommendation.
         *     Safe to re-run: a breached falsifier is never re-alerted.
         */
        post: operations["run_check_alerts_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/live-falsifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Falsifiers
         * @description Every falsifier on a LIVE thesis with its current reading — the
         *     watch-list view. Distance to breach is the UI's arithmetic; the values
         *     here are the record.
         */
        get: operations["live_falsifiers_alerts_live_falsifiers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Allocation */
        get: operations["get_allocation_allocation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_allocation_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_allocation_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_kite_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_kite_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_auth_kite_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Debts */
        put: operations["put_debts_planner_debts_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Goals */
        put: operations["put_goals_planner_goals_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_planner_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/plan/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Plan */
        get: operations["get_latest_plan_planner_plan_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Profile */
        put: operations["put_profile_planner_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_planner_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/temperament-scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Temperament Scenario
         * @description The scenario question, scaled to the user's actual corpus.
         */
        get: operations["temperament_scenario_planner_temperament_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidates
         * @description Deterministic ranking from stored metric_values. Empty is a valid,
         *     explained result — not a failure state.
         */
        get: operations["candidates_research_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Report
         * @description On-demand report generation — 20-60s when the LLM is wired. Refuses
         *     below 60% coverage (docs/07 anti-patterns) and without an API key.
         */
        post: operations["generate_report_research_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_sim_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_sim_positions_get"];
        put?: never;
        /** Post Position */
        post: operations["post_position_sim_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/positions/{position_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Close */
        post: operations["post_close_sim_positions__position_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/run-daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Daily
         * @description Manual trigger for pipeline steps 9-10 until the nightly scheduler
         *     lands with the full pipeline (M5+).
         */
        post: operations["run_daily_sim_run_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sim/theses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Theses */
        get: operations["list_theses_sim_theses_get"];
        put?: never;
        /** Post Thesis */
        post: operations["post_thesis_sim_theses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Field Id */
            field_id: string;
            /** Horizon */
            horizon: string;
            /** Id */
            id: number;
            /** Isin */
            isin: string;
            /** Kind */
            kind: string;
            /** Observed As Of */
            observed_as_of: string;
            /** Observed Value */
            observed_value: string;
            /** Operator */
            operator: string;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Thesis Line */
            thesis_line: string;
            /** Thesis Line Found */
            thesis_line_found: boolean;
            /** Threshold */
            threshold: string;
            /** Tradingsymbol */
            tradingsymbol: string | null;
        };
        /** Allocation */
        Allocation: {
            /** Assumptions Version */
            assumptions_version: string;
            /** Diversification Notes */
            diversification_notes: string[];
            /** Gated Out */
            gated_out: components["schemas"]["GatedVehicle"][];
            /** Horizon Months */
            horizon_months: number;
            /** Lines */
            lines: components["schemas"]["AllocationLine"][];
            /** Plan Version Id */
            plan_version_id: string | null;
            preferences: components["schemas"]["AllocationPreferences"];
            /** Ranked Vehicles */
            ranked_vehicles: components["schemas"]["VehicleScore"][];
            /** Vehicles Version */
            vehicles_version: string;
        };
        /** AllocationLine */
        AllocationLine: {
            bucket: components["schemas"]["HorizonBucket"];
            /** Label */
            label: string;
            /** Lumpsum Inr */
            lumpsum_inr: number;
            /** Monthly Inr */
            monthly_inr: number;
            /** Rationale */
            rationale: string;
            /** Vehicle Id */
            vehicle_id: string;
        };
        /**
         * AllocationPreferences
         * @description The two allocation inputs the planner does not already hold.
         *
         *     self_rated_knowledge defaults LOW: the conservative reading gates
         *     HIGH-knowledge vehicles out until the user claims otherwise.
         *     max_lock_in_months None means the user has stated no constraint;
         *     the lock-in gate then passes and the UI says so.
         */
        AllocationPreferences: {
            /** Max Lock In Months */
            max_lock_in_months?: number | null;
            /** @default LOW */
            self_rated_knowledge: components["schemas"]["Knowledge"];
        };
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
        };
        /** BlockOut */
        BlockOut: {
            /** Content */
            content: string;
            /** Kind */
            kind: string;
            /** Provenance */
            provenance: string;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Composite Pctl */
            composite_pctl: number;
            /** Conviction */
            conviction: string;
            /** Coverage */
            coverage: number;
            /** Isin */
            isin: string;
            /** Tradingsymbol */
            tradingsymbol: string | null;
        };
        /** CandidatesOut */
        CandidatesOut: {
            /** As Of */
            as_of: string | null;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /** Horizon */
            horizon: string;
            /** Message */
            message: string | null;
        };
        /** CheckOut */
        CheckOut: {
            /** As Of */
            as_of: string;
            /** Breached */
            breached: number;
            /** Checked */
            checked: number;
            /** Skipped */
            skipped: string[];
        };
        /** ClosePositionIn */
        ClosePositionIn: {
            /** Journal Note */
            journal_note: string;
            /** Price */
            price?: number | string | null;
            /** Reason */
            reason: string;
        };
        /** DebtIn */
        "DebtIn-Input": {
            /** Annual Rate Pct */
            annual_rate_pct: number | string;
            /** Label */
            label: string;
            /**
             * Min Emi
             * @default 0
             */
            min_emi: number | string;
            /** Principal Outstanding */
            principal_outstanding: number | string;
            /**
             * Tax Deductible
             * @default false
             */
            tax_deductible: boolean;
        };
        /** DebtIn */
        "DebtIn-Output": {
            /** Annual Rate Pct */
            annual_rate_pct: string;
            /** Label */
            label: string;
            /**
             * Min Emi
             * @default 0
             */
            min_emi: number;
            /** Principal Outstanding */
            principal_outstanding: number;
            /**
             * Tax Deductible
             * @default false
             */
            tax_deductible: boolean;
        };
        /** FalsifierIn */
        FalsifierIn: {
            /** Field Id */
            field_id: string;
            /** Human Text */
            human_text: string;
            /** Operator */
            operator: string;
            /** Threshold */
            threshold: number | string;
        };
        /** GateResult */
        GateResult: {
            /** Amount */
            amount: number;
            /** Gate */
            gate: string;
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            status: components["schemas"]["GateStatus"];
        };
        /**
         * GateStatus
         * @enum {string}
         */
        GateStatus: "PASSED" | "BLOCKED" | "INFO";
        /** GatedVehicle */
        GatedVehicle: {
            /** Explanation */
            explanation: string;
            /** Gate */
            gate: string;
            /** Label */
            label: string;
            /** Liquidity Days */
            liquidity_days: number;
            /** Lock In Months */
            lock_in_months: number;
            /** Net Expected Return Pct */
            net_expected_return_pct: string;
            /** Vehicle Id */
            vehicle_id: string;
            /** Volatility Annual Pct */
            volatility_annual_pct: string;
        };
        /** GoalIn */
        "GoalIn-Input": {
            /** Label */
            label: string;
            /** @default SHOULD */
            priority: components["schemas"]["GoalPriority"];
            /** Target Amount */
            target_amount: number | string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
        };
        /** GoalIn */
        "GoalIn-Output": {
            /** Label */
            label: string;
            /** @default SHOULD */
            priority: components["schemas"]["GoalPriority"];
            /** Target Amount */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
        };
        /**
         * GoalPriority
         * @enum {string}
         */
        GoalPriority: "MUST" | "SHOULD" | "WANT";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /**
         * HorizonBucket
         * @enum {string}
         */
        HorizonBucket: "LIQUID_0_12" | "DEBT_12_36" | "HYBRID_36_60" | "EQUITY_60_PLUS";
        /** HorizonSummary */
        HorizonSummary: {
            /** Band Coverage Pct */
            band_coverage_pct: string | null;
            /** Hit Rate Pct */
            hit_rate_pct: string | null;
            /** Horizon */
            horizon: string;
            /** Mean Brier */
            mean_brier: string | null;
            /** N */
            n: number;
            /** N Needed */
            n_needed: number;
            /** Net Alpha Pct */
            net_alpha_pct: string | null;
            /** Severity */
            severity: string;
            /** Verdict */
            verdict: string;
        };
        /**
         * JobStability
         * @enum {string}
         */
        JobStability: "LOW" | "MEDIUM" | "HIGH";
        /**
         * Knowledge
         * @enum {string}
         */
        Knowledge: "LOW" | "MEDIUM" | "HIGH";
        /** LiveFalsifierOut */
        LiveFalsifierOut: {
            /** Breached */
            breached: boolean | null;
            /** Current Value */
            current_value: string | null;
            /** Falsifier Id */
            falsifier_id: string;
            /** Field Id */
            field_id: string;
            /** Horizon */
            horizon: string;
            /** Human Text */
            human_text: string;
            /** Isin */
            isin: string;
            /** Observed As Of */
            observed_as_of: string | null;
            /** Operator */
            operator: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Threshold */
            threshold: string;
            /** Tradingsymbol */
            tradingsymbol: string | null;
        };
        /** ManualThesisIn */
        ManualThesisIn: {
            /** Band Base Pct */
            band_base_pct: number | string;
            /** Band Bear Pct */
            band_bear_pct: number | string;
            /** Band Bull Pct */
            band_bull_pct: number | string;
            /** Conviction */
            conviction: string;
            /**
             * Expires On
             * Format: date
             */
            expires_on: string;
            /** Falsifiers */
            falsifiers: components["schemas"]["FalsifierIn"][];
            /** Horizon */
            horizon: string;
            /** Instrument Token */
            instrument_token?: number | null;
            /** Isin */
            isin: string;
            /** Ref Price */
            ref_price: number | string;
            /** Suggested Size Inr */
            suggested_size_inr: number | string;
            /**
             * Thesis Md
             * @description Your reasoning, frozen at issue
             */
            thesis_md: string;
            /** Tradingsymbol */
            tradingsymbol?: string | null;
        };
        /** MarkRunOut */
        MarkRunOut: {
            /** Marked */
            marked: number;
            /** Scored */
            scored: number;
            /** Skipped */
            skipped: string[];
        };
        /** OpenPositionIn */
        OpenPositionIn: {
            /** Amount Inr */
            amount_inr: number | string;
            /** Price */
            price?: number | string | null;
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
        };
        /** PlanResult */
        PlanResult: {
            /** Assumptions Version */
            assumptions_version: string;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Buffer Current */
            buffer_current: number;
            /** Buffer Eta Months */
            buffer_eta_months: number | null;
            /** Buffer Target */
            buffer_target: number;
            /** Gates */
            gates: components["schemas"]["GateResult"][];
            /** Generated At */
            generated_at?: string | null;
            /** Horizon Buckets */
            horizon_buckets: {
                [key: string]: number;
            };
            /** Investable Lumpsum */
            investable_lumpsum: number;
            /** Investable Monthly */
            investable_monthly: number;
            /** Max Equity Fraction */
            max_equity_fraction: string;
            /** Sensitivity */
            sensitivity: components["schemas"]["SensitivityRow"][];
            /** Spending Recommendations */
            spending_recommendations: string[];
            /** Version Id */
            version_id?: string | null;
        };
        /** PositionOut */
        PositionOut: {
            /** Close Reason */
            close_reason: string | null;
            /** Closed On */
            closed_on: string | null;
            /** Entry Costs Inr */
            entry_costs_inr: number;
            /** Entry Price */
            entry_price: string;
            /** Exit Price */
            exit_price: string | null;
            /** Flag Reason */
            flag_reason: string | null;
            /** Flagged At */
            flagged_at: string | null;
            /** Holding Xirr Pct */
            holding_xirr_pct: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isin */
            isin: string;
            /** Journal Note */
            journal_note: string | null;
            /** Latest Mark */
            latest_mark: {
                [key: string]: unknown;
            } | null;
            /**
             * Opened On
             * Format: date
             */
            opened_on: string;
            /** Qty */
            qty: number;
            /** Realised Pnl Inr */
            realised_pnl_inr: number | null;
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /** Thesis Snapshot Md */
            thesis_snapshot_md: string;
        };
        /** ProfileIn */
        "ProfileIn-Input": {
            /**
             * Dependants
             * @default 0
             */
            dependants: number;
            /** Display Name */
            display_name?: string | null;
            /**
             * Existing Investments
             * @default 0
             */
            existing_investments: number | string;
            /** Fixed Outflow */
            fixed_outflow: number | string;
            /**
             * Income Variability
             * @default 0
             */
            income_variability: number | string;
            /** @default MEDIUM */
            job_stability: components["schemas"]["JobStability"];
            /** Liquid Balance */
            liquid_balance: number | string;
            /** Monthly Inflow */
            monthly_inflow: number | string;
            /** @default SELL_SOME */
            temperament_choice: components["schemas"]["TemperamentChoice"];
            /** Variable Outflow */
            variable_outflow: number | string;
        };
        /** ProfileIn */
        "ProfileIn-Output": {
            /**
             * Dependants
             * @default 0
             */
            dependants: number;
            /** Display Name */
            display_name?: string | null;
            /**
             * Existing Investments
             * @default 0
             */
            existing_investments: number;
            /** Fixed Outflow */
            fixed_outflow: number;
            /**
             * Income Variability
             * @default 0
             */
            income_variability: string;
            /** @default MEDIUM */
            job_stability: components["schemas"]["JobStability"];
            /** Liquid Balance */
            liquid_balance: number;
            /** Monthly Inflow */
            monthly_inflow: number;
            /** @default SELL_SOME */
            temperament_choice: components["schemas"]["TemperamentChoice"];
            /** Variable Outflow */
            variable_outflow: number;
        };
        /** ReportOut */
        ReportOut: {
            /** Blocks */
            blocks: components["schemas"]["BlockOut"][];
            /** Coverage */
            coverage: number;
            /** Horizon */
            horizon: string;
            /** Isin */
            isin: string;
            /** Narrative Included */
            narrative_included: boolean;
        };
        /** ReportRequest */
        ReportRequest: {
            /** Horizon */
            horizon: string;
            /** Isin */
            isin: string;
        };
        /** ScenarioOption */
        ScenarioOption: {
            /** Choice */
            choice: string;
            /** Label */
            label: string;
            /** Tolerated Dd Fraction */
            tolerated_dd_fraction: string;
        };
        /** SensitivityRow */
        SensitivityRow: {
            /** Equity Real Return Pct */
            equity_real_return_pct: string;
            /** Hurdle Pct */
            hurdle_pct: string;
            /** Investable Monthly */
            investable_monthly: number;
            /** Note */
            note: string;
        };
        /**
         * TemperamentChoice
         * @enum {string}
         */
        TemperamentChoice: "SELL_EVERYTHING" | "SELL_SOME" | "HOLD" | "BUY_MORE";
        /** TemperamentScenario */
        TemperamentScenario: {
            /** After Inr */
            after_inr: number;
            /** Before Inr */
            before_inr: number;
            /** Options */
            options: components["schemas"]["ScenarioOption"][];
        };
        /** ThesisOut */
        ThesisOut: {
            /** Band Base Pct */
            band_base_pct: string;
            /** Band Bear Pct */
            band_bear_pct: string;
            /** Band Bull Pct */
            band_bull_pct: string;
            /** Conviction */
            conviction: string;
            /**
             * Expires On
             * Format: date
             */
            expires_on: string;
            /** Falsifiers */
            falsifiers: {
                [key: string]: unknown;
            }[];
            /** Horizon */
            horizon: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isin */
            isin: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Ref Price */
            ref_price: string;
            /** Report Md */
            report_md: string;
            /** Status */
            status: string;
            /** Suggested Size Inr */
            suggested_size_inr: number;
            /** Tradingsymbol */
            tradingsymbol: string | null;
        };
        /** UserState */
        UserState: {
            /** Debts */
            debts: components["schemas"]["DebtIn-Output"][];
            /** Goals */
            goals: components["schemas"]["GoalIn-Output"][];
            profile: components["schemas"]["ProfileIn-Output"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleScore */
        VehicleScore: {
            /** Allocated Lumpsum */
            allocated_lumpsum: number;
            /** Allocated Monthly */
            allocated_monthly: number;
            /** Components */
            components: {
                [key: string]: string;
            };
            /** Effort */
            effort: string;
            /** Knowledge Required */
            knowledge_required: string;
            /** Label */
            label: string;
            /** Liquidity Days */
            liquidity_days: number;
            /** Lock In Months */
            lock_in_months: number;
            /** Net Expected Return Pct */
            net_expected_return_pct: string;
            /** Suitability Pct */
            suitability_pct: string;
            /** Vehicle Id */
            vehicle_id: string;
            /** Volatility Annual Pct */
            volatility_annual_pct: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_alerts_get: {
        parameters: {
            query?: {
                include_acknowledged?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_check_alerts_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOut"];
                };
            };
        };
    };
    live_falsifiers_alerts_live_falsifiers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveFalsifierOut"][];
                };
            };
        };
    };
    acknowledge_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_allocation_allocation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allocation"];
                };
            };
        };
    };
    get_preferences_allocation_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationPreferences"];
                };
            };
        };
    };
    put_preferences_allocation_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_auth_kite_callback_get: {
        parameters: {
            query: {
                request_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_kite_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_auth_kite_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    put_debts_planner_debts_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtIn-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtIn-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_goals_planner_goals_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalIn-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_planner_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
        };
    };
    get_latest_plan_planner_plan_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
        };
    };
    put_profile_planner_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileIn-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_planner_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserState"];
                };
            };
        };
    };
    temperament_scenario_planner_temperament_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperamentScenario"];
                };
            };
        };
    };
    candidates_research_candidates_get: {
        parameters: {
            query?: {
                horizon?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_research_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_sim_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorizonSummary"][];
                };
            };
        };
    };
    list_positions_sim_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"][];
                };
            };
        };
    };
    post_position_sim_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenPositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_close_sim_positions__position_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosePositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_daily_sim_run_daily_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkRunOut"];
                };
            };
        };
    };
    list_theses_sim_theses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisOut"][];
                };
            };
        };
    };
    post_thesis_sim_theses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualThesisIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
