/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_kite_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_auth_kite_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kite/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_auth_kite_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_planner_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Profile */
        put: operations["put_profile_planner_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Debts */
        put: operations["put_debts_planner_debts_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Goals */
        put: operations["put_goals_planner_goals_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_planner_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/plan/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Plan */
        get: operations["get_latest_plan_planner_plan_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planner/temperament-scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Temperament Scenario
         * @description The scenario question, scaled to the user's actual corpus.
         */
        get: operations["temperament_scenario_planner_temperament_scenario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Degraded Reason */
            degraded_reason: string | null;
        };
        /** DebtIn */
        "DebtIn-Input": {
            /** Label */
            label: string;
            /** Principal Outstanding */
            principal_outstanding: number | string;
            /** Annual Rate Pct */
            annual_rate_pct: number | string;
            /**
             * Min Emi
             * @default 0
             */
            min_emi: number | string;
            /**
             * Tax Deductible
             * @default false
             */
            tax_deductible: boolean;
        };
        /** DebtIn */
        "DebtIn-Output": {
            /** Label */
            label: string;
            /** Principal Outstanding */
            principal_outstanding: number;
            /** Annual Rate Pct */
            annual_rate_pct: string;
            /**
             * Min Emi
             * @default 0
             */
            min_emi: number;
            /**
             * Tax Deductible
             * @default false
             */
            tax_deductible: boolean;
        };
        /** GateResult */
        GateResult: {
            /** Gate */
            gate: string;
            /** Label */
            label: string;
            status: components["schemas"]["GateStatus"];
            /** Amount */
            amount: number;
            /** Reason */
            reason: string;
        };
        /**
         * GateStatus
         * @enum {string}
         */
        GateStatus: "PASSED" | "BLOCKED" | "INFO";
        /** GoalIn */
        "GoalIn-Input": {
            /** Label */
            label: string;
            /** Target Amount */
            target_amount: number | string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** @default SHOULD */
            priority: components["schemas"]["GoalPriority"];
        };
        /** GoalIn */
        "GoalIn-Output": {
            /** Label */
            label: string;
            /** Target Amount */
            target_amount: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** @default SHOULD */
            priority: components["schemas"]["GoalPriority"];
        };
        /**
         * GoalPriority
         * @enum {string}
         */
        GoalPriority: "MUST" | "SHOULD" | "WANT";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /**
         * HorizonBucket
         * @enum {string}
         */
        HorizonBucket: "LIQUID_0_12" | "DEBT_12_36" | "HYBRID_36_60" | "EQUITY_60_PLUS";
        /**
         * JobStability
         * @enum {string}
         */
        JobStability: "LOW" | "MEDIUM" | "HIGH";
        /** PlanResult */
        PlanResult: {
            /** Version Id */
            version_id?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Gates */
            gates: components["schemas"]["GateResult"][];
            /** Investable Monthly */
            investable_monthly: number;
            /** Investable Lumpsum */
            investable_lumpsum: number;
            /** Buffer Target */
            buffer_target: number;
            /** Buffer Current */
            buffer_current: number;
            /** Buffer Eta Months */
            buffer_eta_months: number | null;
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Spending Recommendations */
            spending_recommendations: string[];
            /** Max Equity Fraction */
            max_equity_fraction: string;
            /** Horizon Buckets */
            horizon_buckets: {
                [key: string]: number;
            };
            /** Assumptions Version */
            assumptions_version: string;
            /** Sensitivity */
            sensitivity: components["schemas"]["SensitivityRow"][];
        };
        /** ProfileIn */
        "ProfileIn-Input": {
            /** Display Name */
            display_name?: string | null;
            /** Monthly Inflow */
            monthly_inflow: number | string;
            /** Fixed Outflow */
            fixed_outflow: number | string;
            /** Variable Outflow */
            variable_outflow: number | string;
            /** Liquid Balance */
            liquid_balance: number | string;
            /**
             * Existing Investments
             * @default 0
             */
            existing_investments: number | string;
            /**
             * Dependants
             * @default 0
             */
            dependants: number;
            /** @default MEDIUM */
            job_stability: components["schemas"]["JobStability"];
            /**
             * Income Variability
             * @default 0
             */
            income_variability: number | string;
            /** @default SELL_SOME */
            temperament_choice: components["schemas"]["TemperamentChoice"];
        };
        /** ProfileIn */
        "ProfileIn-Output": {
            /** Display Name */
            display_name?: string | null;
            /** Monthly Inflow */
            monthly_inflow: number;
            /** Fixed Outflow */
            fixed_outflow: number;
            /** Variable Outflow */
            variable_outflow: number;
            /** Liquid Balance */
            liquid_balance: number;
            /**
             * Existing Investments
             * @default 0
             */
            existing_investments: number;
            /**
             * Dependants
             * @default 0
             */
            dependants: number;
            /** @default MEDIUM */
            job_stability: components["schemas"]["JobStability"];
            /**
             * Income Variability
             * @default 0
             */
            income_variability: string;
            /** @default SELL_SOME */
            temperament_choice: components["schemas"]["TemperamentChoice"];
        };
        /** ScenarioOption */
        ScenarioOption: {
            /** Choice */
            choice: string;
            /** Label */
            label: string;
            /** Tolerated Dd Fraction */
            tolerated_dd_fraction: string;
        };
        /** SensitivityRow */
        SensitivityRow: {
            /** Equity Real Return Pct */
            equity_real_return_pct: string;
            /** Hurdle Pct */
            hurdle_pct: string;
            /** Investable Monthly */
            investable_monthly: number;
            /** Note */
            note: string;
        };
        /**
         * TemperamentChoice
         * @enum {string}
         */
        TemperamentChoice: "SELL_EVERYTHING" | "SELL_SOME" | "HOLD" | "BUY_MORE";
        /** TemperamentScenario */
        TemperamentScenario: {
            /** Before Inr */
            before_inr: number;
            /** After Inr */
            after_inr: number;
            /** Options */
            options: components["schemas"]["ScenarioOption"][];
        };
        /** UserState */
        UserState: {
            profile: components["schemas"]["ProfileIn-Output"] | null;
            /** Debts */
            debts: components["schemas"]["DebtIn-Output"][];
            /** Goals */
            goals: components["schemas"]["GoalIn-Output"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login_auth_kite_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_auth_kite_callback_get: {
        parameters: {
            query: {
                request_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_auth_kite_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    get_state_planner_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserState"];
                };
            };
        };
    };
    put_profile_planner_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileIn-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_debts_planner_debts_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtIn-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtIn-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_goals_planner_goals_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn-Input"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalIn-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_planner_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
        };
    };
    get_latest_plan_planner_plan_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
        };
    };
    temperament_scenario_planner_temperament_scenario_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperamentScenario"];
                };
            };
        };
    };
}
